import type { Song } from "@/components/music-player"

export const musicData: Song[] = [
  {
    id: "1",
    title: "Sugar & Brownies",
    thumbnail: "/sugar.jpeg?height=200&width=200",
    musicUrl: "Sugar.mp3",
    duration: "4:16",
    artistName: "Dharia",
    color: "#8e44ad",
  },
  {
    id: "2",
    title: "Pasoori",
    thumbnail: "/passori.jpeg?height=200&width=200",
    musicUrl: "Pasoori.mp3",
    duration: "5:24",
    artistName: "Shae Gill",
    color: "#c0392b",
  },
  {
    id: "3",
    title: "Let Me Love You ft Justin Bieber",
    thumbnail: "/let.jpeg?height=200&width=200",
    musicUrl: "DJ Snake.mp3",
    duration: "6:23",
    artistName: "Dj Snake",
    color: "#2980b9",
  },
  {
    id: "4",
    title: "No Lie",
    thumbnail: "/no.jpeg?height=200&width=200",
    musicUrl: "No Lie.mp3",
    duration: "3:10",
    artistName: "Dua Lipa",
    color: "#34495e",
  },
  {
    id: "5",
    title: "Unstoppable",
    thumbnail: "/sia.jpeg?height=200&width=200",
    musicUrl: "Sia.mp3",
    duration: "4:23",
    artistName: "Sia",
    color: "#e67e22",
  },
  {
    id: "6",
    title: "Arcade",
    thumbnail: "arcade.jpeg",
    musicUrl: "Arcade.mp3",
    duration: "5:32",
    artistName: "Arcade",
    color: "#d35400",
  },
  {
    id: "7",
    title: "Rihaa",
    thumbnail: "/rihaa.jpeg?height=200&width=200",
    musicUrl: "Rihaa.mp3",
    duration: "2:23",
    artistName: "Arijit Singh",
    color: "#16a085",
  },
  {
    id: "8",
    title: "Bilionera",
    thumbnail: "/bili.jpeg?height=200&width=200",
    musicUrl: "Bilionera.mp3",
    duration: "3:12",
    artistName: "Dua Lipa",
    color: "#9b59b6",
  },
]

